### PR TITLE
Add LEDify and other

### PR DESCRIPTION
**Pull request by grzmot22**

### CODE REVIEW

**Comment by B--B** [comment]
This works, but the import should be added here https://github.com/JDCTeam/android_system_core/blob/opt-cm-13.0/rootdir/init.rc and then ported here when merging Ramdisk updates, otherwise stock kernel won't work and clean Ramdisk still misses this import

**Comment by grzmot22** [comment]
I know, but I found in my repo this commit https://github.com/grzmot22/android_system_core/commit/ebbecea3a3fbad13138e46e740ffa6392d2ca0ac and I think @dkati will cherry-pick to your repo.

**Comment by B--B** [comment]
Weird, I do not see that commit in our repo, don't know if the repo history has been rewritten and that commit was lost.. BTW

https://github.com/JDCTeam/android_system_core/commit/74a6b0afdbc704049713b77d112047b7b6bc6d08

I've added the import, changes will be merged here at next ramdisk update, sorry but i do not have cm sources in my pc and i can't update this repo

**Comment by grzmot22** [comment]
No problem

**Comment by B--B** [comment]
I close this pull request as it's fixed in core repo, thanks for your help

**Comment by dkati** [comment]
although i still dont have led blinking on boot...i think its based on my kernel edits :/

**Comment by grzmot22** [comment]
I used your kernel with my ramdisk and I had led blinking on boot, but i will check again still working.

**Comment by B--B** [comment]
Have you updated this branch with latest Ramdisk changes? Otherwise the import is still missing

**Comment by dkati** [comment]
.........what a jerk.....

**Pull request closed without merging**
